// Generated by Bisonc++ V4.01.00 on Sun, 26 Jan 2014 01:59:12 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {267, 3}, // 1: program ->  declaration_statement_list procedure_name procedure_body
     {267, 2}, // 2: program ->  procedure_name procedure_body
     {269, 3}, // 3: procedure_name (NAME) ->  NAME '(' ')'
     {270, 4}, // 4: procedure_body ('{') ->  '{' declaration_statement_list basic_block_list '}'
     {270, 3}, // 5: procedure_body ('{') ->  '{' basic_block_list '}'
     {268, 2}, // 6: declaration_statement_list ->  declaration_statement_list declaration_statement
     {268, 1}, // 7: declaration_statement_list ->  declaration_statement
     {272, 3}, // 8: declaration_statement (INTEGER) ->  INTEGER identifier ';'
     {271, 2}, // 9: basic_block_list ->  basic_block_list basic_block
     {271, 1}, // 10: basic_block_list ->  basic_block
     {274, 6}, // 11: basic_block ('<') ->  '<' NAME INTEGER_NUMBER '>' ':' statement_list
     {275, 2}, // 12: statement_list ->  statement_list statement
     {275, 1}, // 13: statement_list ->  statement
     {276, 1}, // 14: statement ->  selection_statement
     {276, 1}, // 15: statement ->  iterative_statement
     {276, 1}, // 16: statement ->  assignment_statement
     {276, 1}, // 17: statement ->  condition_statement
     {276, 1}, // 18: statement ->  compound_statement
     {276, 1}, // 19: statement ->  goto_statement
     {276, 1}, // 20: statement ->  return_statement
     {282, 6}, // 21: goto_statement (GOTO) ->  GOTO '<' NAME INTEGER_NUMBER '>' ';'
     {281, 4}, // 22: compound_statement ('{') ->  '{' declaration_statement_list statement_list '}'
     {278, 1}, // 23: iterative_statement ->  while_statement
     {278, 1}, // 24: iterative_statement ->  for_statement
     {278, 1}, // 25: iterative_statement ->  do_while_statement
     {277, 1}, // 26: selection_statement ->  ifelse_statement
     {287, 5}, // 27: ifelse_statement (IF) ->  IF '(' boolean_expression ')' statement
     {287, 7}, // 28: ifelse_statement (IF) ->  IF '(' boolean_expression ')' statement ELSE statement
     {284, 5}, // 29: while_statement (WHILE) ->  WHILE '(' boolean_expression ')' statement
     {286, 7}, // 30: do_while_statement (DO) ->  DO statement WHILE '(' boolean_expression ')' ';'
     {285, 7}, // 31: for_statement (FOR) ->  FOR '(' comma_separated_assignment comma_separated_booleans comma_separated_assignments_without_semicolon ')' statement
     {289, 1}, // 32: comma_separated_assignment (';') ->  ';'
     {289, 3}, // 33: comma_separated_assignment (',') ->  assignment_statement ',' comma_separated_assignment
     {290, 1}, // 34: comma_separated_booleans (';') ->  ';'
     {290, 3}, // 35: comma_separated_booleans (',') ->  boolean_expression ',' comma_separated_booleans
     {291, 3}, // 36: comma_separated_assignments_without_semicolon (',') ->  assignment_statement ',' comma_separated_assignments_without_semicolon
     {292, 1}, // 37: expression ->  boolean_expression
     {293, 3}, // 38: less_than_expression ('<') ->  less_than_expression '<' arithmetic_expression
     {293, 4}, // 39: less_than_expression ('<') ->  less_than_expression '<' '=' arithmetic_expression
     {293, 1}, // 40: less_than_expression ->  arithmetic_expression
     {295, 3}, // 41: greater_than_expression ('>') ->  greater_than_expression '>' less_than_expression
     {295, 4}, // 42: greater_than_expression ('>') ->  greater_than_expression '>' '=' less_than_expression
     {295, 1}, // 43: greater_than_expression ->  less_than_expression
     {296, 4}, // 44: equality_expression ('=') ->  equality_expression '=' '=' greater_than_expression
     {296, 4}, // 45: equality_expression ('!') ->  equality_expression '!' '=' greater_than_expression
     {296, 1}, // 46: equality_expression ->  greater_than_expression
     {297, 1}, // 47: comparison_expression ->  equality_expression
     {298, 3}, // 48: basic_expression ('(') ->  '(' expression ')'
     {298, 1}, // 49: basic_expression ->  identifier
     {299, 2}, // 50: not_expression ('!') ->  '!' not_expression
     {299, 1}, // 51: not_expression ->  basic_expression
     {300, 4}, // 52: and_expression ('&') ->  and_expression '&' '&' comparison_expression
     {300, 1}, // 53: and_expression ->  comparison_expression
     {301, 4}, // 54: or_expression ('|') ->  or_expression '|' '|' and_expression
     {301, 1}, // 55: or_expression ->  and_expression
     {288, 1}, // 56: boolean_expression ->  or_expression
     {302, 3}, // 57: mult_expression ('*') ->  mult_expression '*' not_expression
     {302, 3}, // 58: mult_expression ('/') ->  mult_expression '/' not_expression
     {302, 1}, // 59: mult_expression ->  not_expression
     {303, 3}, // 60: add_expression ('+') ->  add_expression '+' mult_expression
     {303, 3}, // 61: add_expression ('-') ->  add_expression '-' mult_expression
     {303, 1}, // 62: add_expression ->  mult_expression
     {294, 1}, // 63: arithmetic_expression ->  add_expression
     {279, 4}, // 64: assignment_statement ('=') ->  identifier '=' expression ';'
     {279, 4}, // 65: assignment_statement ('=') ->  identifier '=' constant ';'
     {283, 2}, // 66: return_statement (RETURN) ->  RETURN ';'
     {280, 10}, // 67: condition_statement ('=') ->  identifier '=' '(' boolean_expression ')' '?' expression ':' expression ';'
     {273, 1}, // 68: identifier (NAME) ->  NAME
     {273, 1}, // 69: identifier ->  constant
     {304, 1}, // 70: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {305, 1}, // 71: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 7} },                              
    { {       267}, { 1} }, // program                   
    { {       268}, { 2} }, // declaration_statement_list
    { {       269}, { 3} }, // procedure_name            
    { {       272}, { 4} }, // declaration_statement     
    { {       258}, { 5} }, // NAME                      
    { {       260}, { 6} }, // INTEGER                   
    { {         0}, { 0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 5} },                         
    { {       269}, { 7} }, // procedure_name       
    { {       272}, { 8} }, // declaration_statement
    { {       258}, { 5} }, // NAME                 
    { {       260}, { 6} }, // INTEGER              
    { {         0}, { 0} },                         
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       270}, {  9} }, // procedure_body
    { {       123}, { 10} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 11} }, // '('
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  5} },                  
    { {       273}, { 12} }, // identifier    
    { {       258}, { 13} }, // NAME          
    { {       304}, { 14} }, // constant      
    { {       257}, { 15} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       270}, { 16} }, // procedure_body
    { {       123}, { 10} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  7} },                              
    { {       268}, { 17} }, // declaration_statement_list
    { {       271}, { 18} }, // basic_block_list          
    { {       272}, {  4} }, // declaration_statement     
    { {       274}, { 19} }, // basic_block               
    { {       260}, {  6} }, // INTEGER                   
    { {        60}, { 20} }, // '<'                       
    { {         0}, {  0} },                              
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 21} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 22} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  6} },                         
    { {       271}, { 23} }, // basic_block_list     
    { {       272}, {  8} }, // declaration_statement
    { {       274}, { 19} }, // basic_block          
    { {       260}, {  6} }, // INTEGER              
    { {        60}, { 20} }, // '<'                  
    { {         0}, {  0} },                         
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 24} }, // '}'        
    { {       274}, { 25} }, // basic_block
    { {        60}, { 20} }, // '<'        
    { {         0}, {  0} },               
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 26} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_21[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 27} }, // '}'        
    { {       274}, { 25} }, // basic_block
    { {        60}, { 20} }, // '<'        
    { {         0}, {  0} },               
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },                  
    { {       257}, { 28} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        62}, { 29} }, // '>'
    { {         0}, {  0} },       
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 30} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, { 25} },                        
    { {       275}, { 31} }, // statement_list      
    { {       276}, { 32} }, // statement           
    { {       277}, { 33} }, // selection_statement 
    { {       278}, { 34} }, // iterative_statement 
    { {       279}, { 35} }, // assignment_statement
    { {       280}, { 36} }, // condition_statement 
    { {       281}, { 37} }, // compound_statement  
    { {       282}, { 38} }, // goto_statement      
    { {       283}, { 39} }, // return_statement    
    { {       287}, { 40} }, // ifelse_statement    
    { {       284}, { 41} }, // while_statement     
    { {       285}, { 42} }, // for_statement       
    { {       286}, { 43} }, // do_while_statement  
    { {       273}, { 44} }, // identifier          
    { {       123}, { 45} }, // '{'                 
    { {       266}, { 46} }, // GOTO                
    { {       259}, { 47} }, // RETURN              
    { {       262}, { 48} }, // IF                  
    { {       261}, { 49} }, // WHILE               
    { {       265}, { 50} }, // FOR                 
    { {       264}, { 51} }, // DO                  
    { {       258}, { 13} }, // NAME                
    { {       304}, { 14} }, // constant            
    { {       257}, { 15} }, // INTEGER_NUMBER      
    { {         0}, {  0} },                        
};

SR__ s_31[] =
{
    { { REQ_DEF}, {  24} },                        
    { {     276}, {  52} }, // statement           
    { {     277}, {  33} }, // selection_statement 
    { {     278}, {  34} }, // iterative_statement 
    { {     279}, {  35} }, // assignment_statement
    { {     280}, {  36} }, // condition_statement 
    { {     281}, {  37} }, // compound_statement  
    { {     282}, {  38} }, // goto_statement      
    { {     283}, {  39} }, // return_statement    
    { {     287}, {  40} }, // ifelse_statement    
    { {     284}, {  41} }, // while_statement     
    { {     285}, {  42} }, // for_statement       
    { {     286}, {  43} }, // do_while_statement  
    { {     273}, {  44} }, // identifier          
    { {     123}, {  45} }, // '{'                 
    { {     266}, {  46} }, // GOTO                
    { {     259}, {  47} }, // RETURN              
    { {     262}, {  48} }, // IF                  
    { {     261}, {  49} }, // WHILE               
    { {     265}, {  50} }, // FOR                 
    { {     264}, {  51} }, // DO                  
    { {     258}, {  13} }, // NAME                
    { {     304}, {  14} }, // constant            
    { {     257}, {  15} }, // INTEGER_NUMBER      
    { {       0}, { -11} },                        
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 53} }, // '='
    { {         0}, {  0} },       
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  4} },                              
    { {       268}, { 54} }, // declaration_statement_list
    { {       272}, {  4} }, // declaration_statement     
    { {       260}, {  6} }, // INTEGER                   
    { {         0}, {  0} },                              
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        60}, { 55} }, // '<'
    { {         0}, {  0} },       
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 56} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 57} }, // '('
    { {         0}, {  0} },       
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 58} }, // '('
    { {         0}, {  0} },       
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 59} }, // '('
    { {         0}, {  0} },       
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 24} },                        
    { {       276}, { 60} }, // statement           
    { {       277}, { 33} }, // selection_statement 
    { {       278}, { 34} }, // iterative_statement 
    { {       279}, { 35} }, // assignment_statement
    { {       280}, { 36} }, // condition_statement 
    { {       281}, { 37} }, // compound_statement  
    { {       282}, { 38} }, // goto_statement      
    { {       283}, { 39} }, // return_statement    
    { {       287}, { 40} }, // ifelse_statement    
    { {       284}, { 41} }, // while_statement     
    { {       285}, { 42} }, // for_statement       
    { {       286}, { 43} }, // do_while_statement  
    { {       273}, { 44} }, // identifier          
    { {       123}, { 45} }, // '{'                 
    { {       266}, { 46} }, // GOTO                
    { {       259}, { 47} }, // RETURN              
    { {       262}, { 48} }, // IF                  
    { {       261}, { 49} }, // WHILE               
    { {       265}, { 50} }, // FOR                 
    { {       264}, { 51} }, // DO                  
    { {       258}, { 13} }, // NAME                
    { {       304}, { 14} }, // constant            
    { {       257}, { 15} }, // INTEGER_NUMBER      
    { {         0}, {  0} },                        
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 20} },                           
    { {       292}, { 61} }, // expression             
    { {       304}, { 62} }, // constant               
    { {        40}, { 63} }, // '('                    
    { {       288}, { 64} }, // boolean_expression     
    { {       257}, { 15} }, // INTEGER_NUMBER         
    { {       301}, { 65} }, // or_expression          
    { {       300}, { 66} }, // and_expression         
    { {       297}, { 67} }, // comparison_expression  
    { {       296}, { 68} }, // equality_expression    
    { {       295}, { 69} }, // greater_than_expression
    { {       293}, { 70} }, // less_than_expression   
    { {       294}, { 71} }, // arithmetic_expression  
    { {       303}, { 72} }, // add_expression         
    { {       302}, { 73} }, // mult_expression        
    { {       299}, { 74} }, // not_expression         
    { {        33}, { 75} }, // '!'                    
    { {       298}, { 76} }, // basic_expression       
    { {       273}, { 77} }, // identifier             
    { {       258}, { 13} }, // NAME                   
    { {         0}, {  0} },                           
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 27} },                         
    { {       275}, { 78} }, // statement_list       
    { {       272}, {  8} }, // declaration_statement
    { {       276}, { 32} }, // statement            
    { {       260}, {  6} }, // INTEGER              
    { {       277}, { 33} }, // selection_statement  
    { {       278}, { 34} }, // iterative_statement  
    { {       279}, { 35} }, // assignment_statement 
    { {       280}, { 36} }, // condition_statement  
    { {       281}, { 37} }, // compound_statement   
    { {       282}, { 38} }, // goto_statement       
    { {       283}, { 39} }, // return_statement     
    { {       287}, { 40} }, // ifelse_statement     
    { {       284}, { 41} }, // while_statement      
    { {       285}, { 42} }, // for_statement        
    { {       286}, { 43} }, // do_while_statement   
    { {       273}, { 44} }, // identifier           
    { {       123}, { 45} }, // '{'                  
    { {       266}, { 46} }, // GOTO                 
    { {       259}, { 47} }, // RETURN               
    { {       262}, { 48} }, // IF                   
    { {       261}, { 49} }, // WHILE                
    { {       265}, { 50} }, // FOR                  
    { {       264}, { 51} }, // DO                   
    { {       258}, { 13} }, // NAME                 
    { {       304}, { 14} }, // constant             
    { {       257}, { 15} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 79} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 19} },                           
    { {       288}, { 80} }, // boolean_expression     
    { {       301}, { 65} }, // or_expression          
    { {       300}, { 66} }, // and_expression         
    { {       297}, { 67} }, // comparison_expression  
    { {       296}, { 68} }, // equality_expression    
    { {       295}, { 69} }, // greater_than_expression
    { {       293}, { 70} }, // less_than_expression   
    { {       294}, { 71} }, // arithmetic_expression  
    { {       303}, { 72} }, // add_expression         
    { {       302}, { 73} }, // mult_expression        
    { {       299}, { 74} }, // not_expression         
    { {        33}, { 75} }, // '!'                    
    { {       298}, { 76} }, // basic_expression       
    { {        40}, { 81} }, // '('                    
    { {       273}, { 77} }, // identifier             
    { {       258}, { 13} }, // NAME                   
    { {       304}, { 14} }, // constant               
    { {       257}, { 15} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 19} },                           
    { {       288}, { 82} }, // boolean_expression     
    { {       301}, { 65} }, // or_expression          
    { {       300}, { 66} }, // and_expression         
    { {       297}, { 67} }, // comparison_expression  
    { {       296}, { 68} }, // equality_expression    
    { {       295}, { 69} }, // greater_than_expression
    { {       293}, { 70} }, // less_than_expression   
    { {       294}, { 71} }, // arithmetic_expression  
    { {       303}, { 72} }, // add_expression         
    { {       302}, { 73} }, // mult_expression        
    { {       299}, { 74} }, // not_expression         
    { {        33}, { 75} }, // '!'                    
    { {       298}, { 76} }, // basic_expression       
    { {        40}, { 81} }, // '('                    
    { {       273}, { 77} }, // identifier             
    { {       258}, { 13} }, // NAME                   
    { {       304}, { 14} }, // constant               
    { {       257}, { 15} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  8} },                              
    { {       289}, { 83} }, // comma_separated_assignment
    { {        59}, { 84} }, // ';'                       
    { {       279}, { 85} }, // assignment_statement      
    { {       273}, { 86} }, // identifier                
    { {       258}, { 13} }, // NAME                      
    { {       304}, { 14} }, // constant                  
    { {       257}, { 15} }, // INTEGER_NUMBER            
    { {         0}, {  0} },                              
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       261}, { 87} }, // WHILE
    { {         0}, {  0} },         
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 88} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   2} },       
    { {      59}, {  89} }, // ';'
    { {       0}, { -69} },       
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 20} },                           
    { {       288}, { 90} }, // boolean_expression     
    { {       292}, { 91} }, // expression             
    { {       301}, { 65} }, // or_expression          
    { {       300}, { 66} }, // and_expression         
    { {       297}, { 67} }, // comparison_expression  
    { {       296}, { 68} }, // equality_expression    
    { {       295}, { 69} }, // greater_than_expression
    { {       293}, { 70} }, // less_than_expression   
    { {       294}, { 71} }, // arithmetic_expression  
    { {       303}, { 72} }, // add_expression         
    { {       302}, { 73} }, // mult_expression        
    { {       299}, { 74} }, // not_expression         
    { {        33}, { 75} }, // '!'                    
    { {       298}, { 76} }, // basic_expression       
    { {        40}, { 81} }, // '('                    
    { {       273}, { 77} }, // identifier             
    { {       258}, { 13} }, // NAME                   
    { {       304}, { 14} }, // constant               
    { {       257}, { 15} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   2} },       
    { {     124}, {  92} }, // '|'
    { {       0}, { -56} },       
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   2} },       
    { {      38}, {  93} }, // '&'
    { {       0}, { -55} },       
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   3} },       
    { {      61}, {  94} }, // '='
    { {      33}, {  95} }, // '!'
    { {       0}, { -47} },       
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   2} },       
    { {      62}, {  96} }, // '>'
    { {       0}, { -46} },       
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   2} },       
    { {      60}, {  97} }, // '<'
    { {       0}, { -43} },       
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  98} }, // '+'
    { {      45}, {  99} }, // '-'
    { {       0}, { -63} },       
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 100} }, // '*'
    { {      47}, { 101} }, // '/'
    { {       0}, { -62} },       
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {   9} },                    
    { {       299}, { 102} }, // not_expression  
    { {        33}, {  75} }, // '!'             
    { {       298}, {  76} }, // basic_expression
    { {        40}, {  81} }, // '('             
    { {       273}, {  77} }, // identifier      
    { {       258}, {  13} }, // NAME            
    { {       304}, {  14} }, // constant        
    { {       257}, {  15} }, // INTEGER_NUMBER  
    { {         0}, {   0} },                    
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  25} },                        
    { {       125}, { 103} }, // '}'                 
    { {       276}, {  52} }, // statement           
    { {       277}, {  33} }, // selection_statement 
    { {       278}, {  34} }, // iterative_statement 
    { {       279}, {  35} }, // assignment_statement
    { {       280}, {  36} }, // condition_statement 
    { {       281}, {  37} }, // compound_statement  
    { {       282}, {  38} }, // goto_statement      
    { {       283}, {  39} }, // return_statement    
    { {       287}, {  40} }, // ifelse_statement    
    { {       284}, {  41} }, // while_statement     
    { {       285}, {  42} }, // for_statement       
    { {       286}, {  43} }, // do_while_statement  
    { {       273}, {  44} }, // identifier          
    { {       123}, {  45} }, // '{'                 
    { {       266}, {  46} }, // GOTO                
    { {       259}, {  47} }, // RETURN              
    { {       262}, {  48} }, // IF                  
    { {       261}, {  49} }, // WHILE               
    { {       265}, {  50} }, // FOR                 
    { {       264}, {  51} }, // DO                  
    { {       258}, {  13} }, // NAME                
    { {       304}, {  14} }, // constant            
    { {       257}, {  15} }, // INTEGER_NUMBER      
    { {         0}, {   0} },                        
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {   2} },                  
    { {       257}, { 104} }, // INTEGER_NUMBER
    { {         0}, {   0} },                  
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 105} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, { 20} },                           
    { {       292}, { 91} }, // expression             
    { {       288}, { 64} }, // boolean_expression     
    { {       301}, { 65} }, // or_expression          
    { {       300}, { 66} }, // and_expression         
    { {       297}, { 67} }, // comparison_expression  
    { {       296}, { 68} }, // equality_expression    
    { {       295}, { 69} }, // greater_than_expression
    { {       293}, { 70} }, // less_than_expression   
    { {       294}, { 71} }, // arithmetic_expression  
    { {       303}, { 72} }, // add_expression         
    { {       302}, { 73} }, // mult_expression        
    { {       299}, { 74} }, // not_expression         
    { {        33}, { 75} }, // '!'                    
    { {       298}, { 76} }, // basic_expression       
    { {        40}, { 81} }, // '('                    
    { {       273}, { 77} }, // identifier             
    { {       258}, { 13} }, // NAME                   
    { {       304}, { 14} }, // constant               
    { {       257}, { 15} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 106} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  21} },                            
    { {       290}, { 107} }, // comma_separated_booleans
    { {        59}, { 108} }, // ';'                     
    { {       288}, { 109} }, // boolean_expression      
    { {       301}, {  65} }, // or_expression           
    { {       300}, {  66} }, // and_expression          
    { {       297}, {  67} }, // comparison_expression   
    { {       296}, {  68} }, // equality_expression     
    { {       295}, {  69} }, // greater_than_expression 
    { {       293}, {  70} }, // less_than_expression    
    { {       294}, {  71} }, // arithmetic_expression   
    { {       303}, {  72} }, // add_expression          
    { {       302}, {  73} }, // mult_expression         
    { {       299}, {  74} }, // not_expression          
    { {        33}, {  75} }, // '!'                     
    { {       298}, {  76} }, // basic_expression        
    { {        40}, {  81} }, // '('                     
    { {       273}, {  77} }, // identifier              
    { {       258}, {  13} }, // NAME                    
    { {       304}, {  14} }, // constant                
    { {       257}, {  15} }, // INTEGER_NUMBER          
    { {         0}, {   0} },                            
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        44}, { 110} }, // ','
    { {         0}, {   0} },       
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        61}, { 111} }, // '='
    { {         0}, {   0} },       
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        40}, { 112} }, // '('
    { {         0}, {   0} },       
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   2} },       
    { {      41}, { 113} }, // ')'
    { {       0}, { -37} },       
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 114} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       124}, { 115} }, // '|'
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        38}, { 116} }, // '&'
    { {         0}, {   0} },       
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        61}, { 117} }, // '='
    { {         0}, {   0} },       
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        61}, { 118} }, // '='
    { {         0}, {   0} },       
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  14} },                         
    { {       293}, { 119} }, // less_than_expression 
    { {        61}, { 120} }, // '='                  
    { {       294}, {  71} }, // arithmetic_expression
    { {       303}, {  72} }, // add_expression       
    { {       302}, {  73} }, // mult_expression      
    { {       299}, {  74} }, // not_expression       
    { {        33}, {  75} }, // '!'                  
    { {       298}, {  76} }, // basic_expression     
    { {        40}, {  81} }, // '('                  
    { {       273}, {  77} }, // identifier           
    { {       258}, {  13} }, // NAME                 
    { {       304}, {  14} }, // constant             
    { {       257}, {  15} }, // INTEGER_NUMBER       
    { {         0}, {   0} },                         
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {  13} },                         
    { {       294}, { 121} }, // arithmetic_expression
    { {        61}, { 122} }, // '='                  
    { {       303}, {  72} }, // add_expression       
    { {       302}, {  73} }, // mult_expression      
    { {       299}, {  74} }, // not_expression       
    { {        33}, {  75} }, // '!'                  
    { {       298}, {  76} }, // basic_expression     
    { {        40}, {  81} }, // '('                  
    { {       273}, {  77} }, // identifier           
    { {       258}, {  13} }, // NAME                 
    { {       304}, {  14} }, // constant             
    { {       257}, {  15} }, // INTEGER_NUMBER       
    { {         0}, {   0} },                         
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {  10} },                    
    { {       302}, { 123} }, // mult_expression 
    { {       299}, {  74} }, // not_expression  
    { {        33}, {  75} }, // '!'             
    { {       298}, {  76} }, // basic_expression
    { {        40}, {  81} }, // '('             
    { {       273}, {  77} }, // identifier      
    { {       258}, {  13} }, // NAME            
    { {       304}, {  14} }, // constant        
    { {       257}, {  15} }, // INTEGER_NUMBER  
    { {         0}, {   0} },                    
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {  10} },                    
    { {       302}, { 124} }, // mult_expression 
    { {       299}, {  74} }, // not_expression  
    { {        33}, {  75} }, // '!'             
    { {       298}, {  76} }, // basic_expression
    { {        40}, {  81} }, // '('             
    { {       273}, {  77} }, // identifier      
    { {       258}, {  13} }, // NAME            
    { {       304}, {  14} }, // constant        
    { {       257}, {  15} }, // INTEGER_NUMBER  
    { {         0}, {   0} },                    
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {   9} },                    
    { {       299}, { 125} }, // not_expression  
    { {        33}, {  75} }, // '!'             
    { {       298}, {  76} }, // basic_expression
    { {        40}, {  81} }, // '('             
    { {       273}, {  77} }, // identifier      
    { {       258}, {  13} }, // NAME            
    { {       304}, {  14} }, // constant        
    { {       257}, {  15} }, // INTEGER_NUMBER  
    { {         0}, {   0} },                    
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   9} },                    
    { {       299}, { 126} }, // not_expression  
    { {        33}, {  75} }, // '!'             
    { {       298}, {  76} }, // basic_expression
    { {        40}, {  81} }, // '('             
    { {       273}, {  77} }, // identifier      
    { {       258}, {  13} }, // NAME            
    { {       304}, {  14} }, // constant        
    { {       257}, {  15} }, // INTEGER_NUMBER  
    { {         0}, {   0} },                    
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        62}, { 127} }, // '>'
    { {         0}, {   0} },       
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {  24} },                        
    { {       276}, { 128} }, // statement           
    { {       277}, {  33} }, // selection_statement 
    { {       278}, {  34} }, // iterative_statement 
    { {       279}, {  35} }, // assignment_statement
    { {       280}, {  36} }, // condition_statement 
    { {       281}, {  37} }, // compound_statement  
    { {       282}, {  38} }, // goto_statement      
    { {       283}, {  39} }, // return_statement    
    { {       287}, {  40} }, // ifelse_statement    
    { {       284}, {  41} }, // while_statement     
    { {       285}, {  42} }, // for_statement       
    { {       286}, {  43} }, // do_while_statement  
    { {       273}, {  44} }, // identifier          
    { {       123}, {  45} }, // '{'                 
    { {       266}, {  46} }, // GOTO                
    { {       259}, {  47} }, // RETURN              
    { {       262}, {  48} }, // IF                  
    { {       261}, {  49} }, // WHILE               
    { {       265}, {  50} }, // FOR                 
    { {       264}, {  51} }, // DO                  
    { {       258}, {  13} }, // NAME                
    { {       304}, {  14} }, // constant            
    { {       257}, {  15} }, // INTEGER_NUMBER      
    { {         0}, {   0} },                        
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {  24} },                        
    { {       276}, { 129} }, // statement           
    { {       277}, {  33} }, // selection_statement 
    { {       278}, {  34} }, // iterative_statement 
    { {       279}, {  35} }, // assignment_statement
    { {       280}, {  36} }, // condition_statement 
    { {       281}, {  37} }, // compound_statement  
    { {       282}, {  38} }, // goto_statement      
    { {       283}, {  39} }, // return_statement    
    { {       287}, {  40} }, // ifelse_statement    
    { {       284}, {  41} }, // while_statement     
    { {       285}, {  42} }, // for_statement       
    { {       286}, {  43} }, // do_while_statement  
    { {       273}, {  44} }, // identifier          
    { {       123}, {  45} }, // '{'                 
    { {       266}, {  46} }, // GOTO                
    { {       259}, {  47} }, // RETURN              
    { {       262}, {  48} }, // IF                  
    { {       261}, {  49} }, // WHILE               
    { {       265}, {  50} }, // FOR                 
    { {       264}, {  51} }, // DO                  
    { {       258}, {  13} }, // NAME                
    { {       304}, {  14} }, // constant            
    { {       257}, {  15} }, // INTEGER_NUMBER      
    { {         0}, {   0} },                        
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {   7} },                                                 
    { {       291}, { 130} }, // comma_separated_assignments_without_semicolon
    { {       279}, { 131} }, // assignment_statement                         
    { {       273}, {  86} }, // identifier                                   
    { {       258}, {  13} }, // NAME                                         
    { {       304}, {  14} }, // constant                                     
    { {       257}, {  15} }, // INTEGER_NUMBER                               
    { {         0}, {   0} },                                                 
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        44}, { 132} }, // ','
    { {         0}, {   0} },       
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   8} },                              
    { {       289}, { 133} }, // comma_separated_assignment
    { {        59}, {  84} }, // ';'                       
    { {       279}, {  85} }, // assignment_statement      
    { {       273}, {  86} }, // identifier                
    { {       258}, {  13} }, // NAME                      
    { {       304}, {  14} }, // constant                  
    { {       257}, {  15} }, // INTEGER_NUMBER            
    { {         0}, {   0} },                              
};

SR__ s_111[] =
{
    { { REQ_TOKEN}, { 20} },                           
    { {       292}, { 61} }, // expression             
    { {       304}, { 62} }, // constant               
    { {       288}, { 64} }, // boolean_expression     
    { {       257}, { 15} }, // INTEGER_NUMBER         
    { {       301}, { 65} }, // or_expression          
    { {       300}, { 66} }, // and_expression         
    { {       297}, { 67} }, // comparison_expression  
    { {       296}, { 68} }, // equality_expression    
    { {       295}, { 69} }, // greater_than_expression
    { {       293}, { 70} }, // less_than_expression   
    { {       294}, { 71} }, // arithmetic_expression  
    { {       303}, { 72} }, // add_expression         
    { {       302}, { 73} }, // mult_expression        
    { {       299}, { 74} }, // not_expression         
    { {        33}, { 75} }, // '!'                    
    { {       298}, { 76} }, // basic_expression       
    { {        40}, { 81} }, // '('                    
    { {       273}, { 77} }, // identifier             
    { {       258}, { 13} }, // NAME                   
    { {         0}, {  0} },                           
};

SR__ s_112[] =
{
    { { REQ_TOKEN}, {  19} },                           
    { {       288}, { 134} }, // boolean_expression     
    { {       301}, {  65} }, // or_expression          
    { {       300}, {  66} }, // and_expression         
    { {       297}, {  67} }, // comparison_expression  
    { {       296}, {  68} }, // equality_expression    
    { {       295}, {  69} }, // greater_than_expression
    { {       293}, {  70} }, // less_than_expression   
    { {       294}, {  71} }, // arithmetic_expression  
    { {       303}, {  72} }, // add_expression         
    { {       302}, {  73} }, // mult_expression        
    { {       299}, {  74} }, // not_expression         
    { {        33}, {  75} }, // '!'                    
    { {       298}, {  76} }, // basic_expression       
    { {        40}, {  81} }, // '('                    
    { {       273}, {  77} }, // identifier             
    { {       258}, {  13} }, // NAME                   
    { {       304}, {  14} }, // constant               
    { {       257}, {  15} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        63}, { 135} }, // '?'
    { {         0}, {   0} },       
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {  17} },                           
    { {       300}, { 136} }, // and_expression         
    { {       297}, {  67} }, // comparison_expression  
    { {       296}, {  68} }, // equality_expression    
    { {       295}, {  69} }, // greater_than_expression
    { {       293}, {  70} }, // less_than_expression   
    { {       294}, {  71} }, // arithmetic_expression  
    { {       303}, {  72} }, // add_expression         
    { {       302}, {  73} }, // mult_expression        
    { {       299}, {  74} }, // not_expression         
    { {        33}, {  75} }, // '!'                    
    { {       298}, {  76} }, // basic_expression       
    { {        40}, {  81} }, // '('                    
    { {       273}, {  77} }, // identifier             
    { {       258}, {  13} }, // NAME                   
    { {       304}, {  14} }, // constant               
    { {       257}, {  15} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {  16} },                           
    { {       297}, { 137} }, // comparison_expression  
    { {       296}, {  68} }, // equality_expression    
    { {       295}, {  69} }, // greater_than_expression
    { {       293}, {  70} }, // less_than_expression   
    { {       294}, {  71} }, // arithmetic_expression  
    { {       303}, {  72} }, // add_expression         
    { {       302}, {  73} }, // mult_expression        
    { {       299}, {  74} }, // not_expression         
    { {        33}, {  75} }, // '!'                    
    { {       298}, {  76} }, // basic_expression       
    { {        40}, {  81} }, // '('                    
    { {       273}, {  77} }, // identifier             
    { {       258}, {  13} }, // NAME                   
    { {       304}, {  14} }, // constant               
    { {       257}, {  15} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_117[] =
{
    { { REQ_TOKEN}, {  14} },                           
    { {       295}, { 138} }, // greater_than_expression
    { {       293}, {  70} }, // less_than_expression   
    { {       294}, {  71} }, // arithmetic_expression  
    { {       303}, {  72} }, // add_expression         
    { {       302}, {  73} }, // mult_expression        
    { {       299}, {  74} }, // not_expression         
    { {        33}, {  75} }, // '!'                    
    { {       298}, {  76} }, // basic_expression       
    { {        40}, {  81} }, // '('                    
    { {       273}, {  77} }, // identifier             
    { {       258}, {  13} }, // NAME                   
    { {       304}, {  14} }, // constant               
    { {       257}, {  15} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_118[] =
{
    { { REQ_TOKEN}, {  14} },                           
    { {       295}, { 139} }, // greater_than_expression
    { {       293}, {  70} }, // less_than_expression   
    { {       294}, {  71} }, // arithmetic_expression  
    { {       303}, {  72} }, // add_expression         
    { {       302}, {  73} }, // mult_expression        
    { {       299}, {  74} }, // not_expression         
    { {        33}, {  75} }, // '!'                    
    { {       298}, {  76} }, // basic_expression       
    { {        40}, {  81} }, // '('                    
    { {       273}, {  77} }, // identifier             
    { {       258}, {  13} }, // NAME                   
    { {       304}, {  14} }, // constant               
    { {       257}, {  15} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_119[] =
{
    { { REQ_DEF}, {   2} },       
    { {      60}, {  97} }, // '<'
    { {       0}, { -41} },       
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {  13} },                         
    { {       293}, { 140} }, // less_than_expression 
    { {       294}, {  71} }, // arithmetic_expression
    { {       303}, {  72} }, // add_expression       
    { {       302}, {  73} }, // mult_expression      
    { {       299}, {  74} }, // not_expression       
    { {        33}, {  75} }, // '!'                  
    { {       298}, {  76} }, // basic_expression     
    { {        40}, {  81} }, // '('                  
    { {       273}, {  77} }, // identifier           
    { {       258}, {  13} }, // NAME                 
    { {       304}, {  14} }, // constant             
    { {       257}, {  15} }, // INTEGER_NUMBER       
    { {         0}, {   0} },                         
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       294}, { 141} }, // arithmetic_expression
    { {       303}, {  72} }, // add_expression       
    { {       302}, {  73} }, // mult_expression      
    { {       299}, {  74} }, // not_expression       
    { {        33}, {  75} }, // '!'                  
    { {       298}, {  76} }, // basic_expression     
    { {        40}, {  81} }, // '('                  
    { {       273}, {  77} }, // identifier           
    { {       258}, {  13} }, // NAME                 
    { {       304}, {  14} }, // constant             
    { {       257}, {  15} }, // INTEGER_NUMBER       
    { {         0}, {   0} },                         
};

SR__ s_123[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 100} }, // '*'
    { {      47}, { 101} }, // '/'
    { {       0}, { -60} },       
};

SR__ s_124[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, { 100} }, // '*'
    { {      47}, { 101} }, // '/'
    { {       0}, { -61} },       
};

SR__ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 142} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_128[] =
{
    { { REQ_DEF}, {   2} },        
    { {     263}, { 143} }, // ELSE
    { {       0}, { -27} },        
};

SR__ s_129[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_130[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 144} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        44}, { 145} }, // ','
    { {         0}, {   0} },       
};

SR__ s_132[] =
{
    { { REQ_TOKEN}, {  21} },                            
    { {       290}, { 146} }, // comma_separated_booleans
    { {        59}, { 108} }, // ';'                     
    { {       288}, { 109} }, // boolean_expression      
    { {       301}, {  65} }, // or_expression           
    { {       300}, {  66} }, // and_expression          
    { {       297}, {  67} }, // comparison_expression   
    { {       296}, {  68} }, // equality_expression     
    { {       295}, {  69} }, // greater_than_expression 
    { {       293}, {  70} }, // less_than_expression    
    { {       294}, {  71} }, // arithmetic_expression   
    { {       303}, {  72} }, // add_expression          
    { {       302}, {  73} }, // mult_expression         
    { {       299}, {  74} }, // not_expression          
    { {        33}, {  75} }, // '!'                     
    { {       298}, {  76} }, // basic_expression        
    { {        40}, {  81} }, // '('                     
    { {       273}, {  77} }, // identifier              
    { {       258}, {  13} }, // NAME                    
    { {       304}, {  14} }, // constant                
    { {       257}, {  15} }, // INTEGER_NUMBER          
    { {         0}, {   0} },                            
};

SR__ s_133[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 147} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_135[] =
{
    { { REQ_TOKEN}, {  20} },                           
    { {       292}, { 148} }, // expression             
    { {       288}, {  64} }, // boolean_expression     
    { {       301}, {  65} }, // or_expression          
    { {       300}, {  66} }, // and_expression         
    { {       297}, {  67} }, // comparison_expression  
    { {       296}, {  68} }, // equality_expression    
    { {       295}, {  69} }, // greater_than_expression
    { {       293}, {  70} }, // less_than_expression   
    { {       294}, {  71} }, // arithmetic_expression  
    { {       303}, {  72} }, // add_expression         
    { {       302}, {  73} }, // mult_expression        
    { {       299}, {  74} }, // not_expression         
    { {        33}, {  75} }, // '!'                    
    { {       298}, {  76} }, // basic_expression       
    { {        40}, {  81} }, // '('                    
    { {       273}, {  77} }, // identifier             
    { {       258}, {  13} }, // NAME                   
    { {       304}, {  14} }, // constant               
    { {       257}, {  15} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_136[] =
{
    { { REQ_DEF}, {   2} },       
    { {      38}, {  93} }, // '&'
    { {       0}, { -54} },       
};

SR__ s_137[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_138[] =
{
    { { REQ_DEF}, {   2} },       
    { {      62}, {  96} }, // '>'
    { {       0}, { -44} },       
};

SR__ s_139[] =
{
    { { REQ_DEF}, {   2} },       
    { {      62}, {  96} }, // '>'
    { {       0}, { -45} },       
};

SR__ s_140[] =
{
    { { REQ_DEF}, {   2} },       
    { {      60}, {  97} }, // '<'
    { {       0}, { -42} },       
};

SR__ s_141[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_142[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_143[] =
{
    { { REQ_TOKEN}, {  24} },                        
    { {       276}, { 149} }, // statement           
    { {       277}, {  33} }, // selection_statement 
    { {       278}, {  34} }, // iterative_statement 
    { {       279}, {  35} }, // assignment_statement
    { {       280}, {  36} }, // condition_statement 
    { {       281}, {  37} }, // compound_statement  
    { {       282}, {  38} }, // goto_statement      
    { {       283}, {  39} }, // return_statement    
    { {       287}, {  40} }, // ifelse_statement    
    { {       284}, {  41} }, // while_statement     
    { {       285}, {  42} }, // for_statement       
    { {       286}, {  43} }, // do_while_statement  
    { {       273}, {  44} }, // identifier          
    { {       123}, {  45} }, // '{'                 
    { {       266}, {  46} }, // GOTO                
    { {       259}, {  47} }, // RETURN              
    { {       262}, {  48} }, // IF                  
    { {       261}, {  49} }, // WHILE               
    { {       265}, {  50} }, // FOR                 
    { {       264}, {  51} }, // DO                  
    { {       258}, {  13} }, // NAME                
    { {       304}, {  14} }, // constant            
    { {       257}, {  15} }, // INTEGER_NUMBER      
    { {         0}, {   0} },                        
};

SR__ s_144[] =
{
    { { REQ_TOKEN}, {  24} },                        
    { {       276}, { 150} }, // statement           
    { {       277}, {  33} }, // selection_statement 
    { {       278}, {  34} }, // iterative_statement 
    { {       279}, {  35} }, // assignment_statement
    { {       280}, {  36} }, // condition_statement 
    { {       281}, {  37} }, // compound_statement  
    { {       282}, {  38} }, // goto_statement      
    { {       283}, {  39} }, // return_statement    
    { {       287}, {  40} }, // ifelse_statement    
    { {       284}, {  41} }, // while_statement     
    { {       285}, {  42} }, // for_statement       
    { {       286}, {  43} }, // do_while_statement  
    { {       273}, {  44} }, // identifier          
    { {       123}, {  45} }, // '{'                 
    { {       266}, {  46} }, // GOTO                
    { {       259}, {  47} }, // RETURN              
    { {       262}, {  48} }, // IF                  
    { {       261}, {  49} }, // WHILE               
    { {       265}, {  50} }, // FOR                 
    { {       264}, {  51} }, // DO                  
    { {       258}, {  13} }, // NAME                
    { {       304}, {  14} }, // constant            
    { {       257}, {  15} }, // INTEGER_NUMBER      
    { {         0}, {   0} },                        
};

SR__ s_145[] =
{
    { { REQ_TOKEN}, {   7} },                                                 
    { {       291}, { 151} }, // comma_separated_assignments_without_semicolon
    { {       279}, { 131} }, // assignment_statement                         
    { {       273}, {  86} }, // identifier                                   
    { {       258}, {  13} }, // NAME                                         
    { {       304}, {  14} }, // constant                                     
    { {       257}, {  15} }, // INTEGER_NUMBER                               
    { {         0}, {   0} },                                                 
};

SR__ s_146[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_147[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 152} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_148[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        58}, { 153} }, // ':'
    { {         0}, {   0} },       
};

SR__ s_149[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_150[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_151[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_152[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_153[] =
{
    { { REQ_TOKEN}, {  20} },                           
    { {       292}, { 154} }, // expression             
    { {       288}, {  64} }, // boolean_expression     
    { {       301}, {  65} }, // or_expression          
    { {       300}, {  66} }, // and_expression         
    { {       297}, {  67} }, // comparison_expression  
    { {       296}, {  68} }, // equality_expression    
    { {       295}, {  69} }, // greater_than_expression
    { {       293}, {  70} }, // less_than_expression   
    { {       294}, {  71} }, // arithmetic_expression  
    { {       303}, {  72} }, // add_expression         
    { {       302}, {  73} }, // mult_expression        
    { {       299}, {  74} }, // not_expression         
    { {        33}, {  75} }, // '!'                    
    { {       298}, {  76} }, // basic_expression       
    { {        40}, {  81} }, // '('                    
    { {       273}, {  77} }, // identifier             
    { {       258}, {  13} }, // NAME                   
    { {       304}, {  14} }, // constant               
    { {       257}, {  15} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_154[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 155} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_155[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,  s_153,  s_154,  s_155,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}




