// Generated by Bisonc++ V4.01.00 on Mon, 27 Jan 2014 01:34:59 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {264, 4}, // 1: program ->  declaration_statement_list procedure_name #0001 procedure_body
     {268, 0}, // 2: #0001 ->  <empty>
     {264, 3}, // 3: program ->  procedure_name #0002 procedure_body
     {269, 0}, // 4: #0002 ->  <empty>
     {266, 3}, // 5: procedure_name (NAME) ->  NAME '(' ')'
     {267, 5}, // 6: procedure_body ('{') ->  '{' declaration_statement_list #0003 basic_block_list '}'
     {271, 0}, // 7: #0003 ->  <empty>
     {267, 3}, // 8: procedure_body ('{') ->  '{' basic_block_list '}'
     {265, 2}, // 9: declaration_statement_list ->  declaration_statement_list declaration_statement
     {265, 1}, // 10: declaration_statement_list ->  declaration_statement
     {272, 3}, // 11: declaration_statement (INTEGER) ->  INTEGER identifier ';'
     {270, 2}, // 12: basic_block_list ->  basic_block_list basic_block
     {270, 1}, // 13: basic_block_list ->  basic_block
     {274, 6}, // 14: basic_block ('<') ->  '<' NAME INTEGER_NUMBER '>' ':' statement_list
     {274, 7}, // 15: basic_block ('<') ->  '<' NAME INTEGER_NUMBER '>' ':' statement_list ifelse_statement
     {274, 6}, // 16: basic_block ('<') ->  '<' NAME INTEGER_NUMBER '>' ':' ifelse_statement
     {275, 2}, // 17: statement_list ->  statement_list statement
     {275, 1}, // 18: statement_list ->  statement
     {277, 1}, // 19: statement ->  assignment_statement
     {277, 1}, // 20: statement ->  goto_statement
     {277, 1}, // 21: statement ->  return_statement
     {279, 6}, // 22: goto_statement (GOTO) ->  GOTO '<' NAME INTEGER_NUMBER '>' ';'
     {276, 7}, // 23: ifelse_statement (IF) ->  IF '(' expression ')' goto_statement ELSE goto_statement
     {281, 1}, // 24: expression ->  boolean_expression
     {283, 3}, // 25: less_than_expression ('<') ->  less_than_expression '<' arithmetic_expression
     {283, 4}, // 26: less_than_expression ('<') ->  less_than_expression '<' '=' arithmetic_expression
     {283, 1}, // 27: less_than_expression ->  arithmetic_expression
     {285, 3}, // 28: greater_than_expression ('>') ->  greater_than_expression '>' less_than_expression
     {285, 4}, // 29: greater_than_expression ('>') ->  greater_than_expression '>' '=' less_than_expression
     {285, 1}, // 30: greater_than_expression ->  less_than_expression
     {286, 4}, // 31: equality_expression ('=') ->  equality_expression '=' '=' greater_than_expression
     {286, 4}, // 32: equality_expression ('!') ->  equality_expression '!' '=' greater_than_expression
     {286, 1}, // 33: equality_expression ->  greater_than_expression
     {287, 1}, // 34: comparison_expression ->  equality_expression
     {288, 3}, // 35: basic_expression ('(') ->  '(' expression ')'
     {288, 1}, // 36: basic_expression ->  identifier
     {288, 1}, // 37: basic_expression ->  constant
     {290, 2}, // 38: not_expression ('!') ->  '!' not_expression
     {290, 1}, // 39: not_expression ->  basic_expression
     {291, 4}, // 40: and_expression ('&') ->  and_expression '&' '&' comparison_expression
     {291, 1}, // 41: and_expression ->  comparison_expression
     {292, 4}, // 42: or_expression ('|') ->  or_expression '|' '|' and_expression
     {292, 1}, // 43: or_expression ->  and_expression
     {282, 1}, // 44: boolean_expression ->  or_expression
     {293, 3}, // 45: mult_expression ('*') ->  mult_expression '*' not_expression
     {293, 3}, // 46: mult_expression ('/') ->  mult_expression '/' not_expression
     {293, 1}, // 47: mult_expression ->  not_expression
     {294, 3}, // 48: add_expression ('+') ->  add_expression '+' mult_expression
     {294, 3}, // 49: add_expression ('-') ->  add_expression '-' mult_expression
     {294, 1}, // 50: add_expression ->  mult_expression
     {284, 1}, // 51: arithmetic_expression ->  add_expression
     {278, 4}, // 52: assignment_statement ('=') ->  identifier '=' expression ';'
     {280, 2}, // 53: return_statement (RETURN) ->  RETURN ';'
     {273, 1}, // 54: identifier (NAME) ->  NAME
     {289, 1}, // 55: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {295, 1}, // 56: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 7} },                              
    { {       264}, { 1} }, // program                   
    { {       265}, { 2} }, // declaration_statement_list
    { {       266}, { 3} }, // procedure_name            
    { {       272}, { 4} }, // declaration_statement     
    { {       258}, { 5} }, // NAME                      
    { {       260}, { 6} }, // INTEGER                   
    { {         0}, { 0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 5} },                         
    { {       266}, { 7} }, // procedure_name       
    { {       272}, { 8} }, // declaration_statement
    { {       258}, { 5} }, // NAME                 
    { {       260}, { 6} }, // INTEGER              
    { {         0}, { 0} },                         
};

SR__ s_3[] =
{
    { { DEF_RED}, {  2} },         
    { {     269}, {  9} }, // #0002
    { {       0}, { -4} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 10} }, // '('
    { {         0}, {  0} },       
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       273}, { 11} }, // identifier
    { {       258}, { 12} }, // NAME      
    { {         0}, {  0} },              
};

SR__ s_7[] =
{
    { { DEF_RED}, {  2} },         
    { {     268}, { 13} }, // #0001
    { {       0}, { -2} },         
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       267}, { 14} }, // procedure_body
    { {       123}, { 15} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 16} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 17} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       267}, { 18} }, // procedure_body
    { {       123}, { 15} }, // '{'           
    { {         0}, {  0} },                  
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  7} },                              
    { {       265}, { 19} }, // declaration_statement_list
    { {       270}, { 20} }, // basic_block_list          
    { {       272}, {  4} }, // declaration_statement     
    { {       274}, { 21} }, // basic_block               
    { {       260}, {  6} }, // INTEGER                   
    { {        60}, { 22} }, // '<'                       
    { {         0}, {  0} },                              
};

SR__ s_16[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_19[] =
{
    { { REQ_DEF}, {  4} },                         
    { {     271}, { 23} }, // #0003                
    { {     272}, {  8} }, // declaration_statement
    { {     260}, {  6} }, // INTEGER              
    { {       0}, { -7} },                         
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 24} }, // '}'        
    { {       274}, { 25} }, // basic_block
    { {        60}, { 22} }, // '<'        
    { {         0}, {  0} },               
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 26} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       270}, { 27} }, // basic_block_list
    { {       274}, { 21} }, // basic_block     
    { {        60}, { 22} }, // '<'             
    { {         0}, {  0} },                    
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },                  
    { {       257}, { 28} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  4} },               
    { {       125}, { 29} }, // '}'        
    { {       274}, { 25} }, // basic_block
    { {        60}, { 22} }, // '<'        
    { {         0}, {  0} },               
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        62}, { 30} }, // '>'
    { {         0}, {  0} },       
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        58}, { 31} }, // ':'
    { {         0}, {  0} },       
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, { 12} },                        
    { {       275}, { 32} }, // statement_list      
    { {       276}, { 33} }, // ifelse_statement    
    { {       277}, { 34} }, // statement           
    { {       261}, { 35} }, // IF                  
    { {       278}, { 36} }, // assignment_statement
    { {       279}, { 37} }, // goto_statement      
    { {       280}, { 38} }, // return_statement    
    { {       273}, { 39} }, // identifier          
    { {       263}, { 40} }, // GOTO                
    { {       259}, { 41} }, // RETURN              
    { {       258}, { 12} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_32[] =
{
    { { REQ_DEF}, {  11} },                        
    { {     276}, {  42} }, // ifelse_statement    
    { {     277}, {  43} }, // statement           
    { {     261}, {  35} }, // IF                  
    { {     278}, {  36} }, // assignment_statement
    { {     279}, {  37} }, // goto_statement      
    { {     280}, {  38} }, // return_statement    
    { {     273}, {  39} }, // identifier          
    { {     263}, {  40} }, // GOTO                
    { {     259}, {  41} }, // RETURN              
    { {     258}, {  12} }, // NAME                
    { {       0}, { -14} },                        
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 44} }, // '('
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 45} }, // '='
    { {         0}, {  0} },       
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        60}, { 46} }, // '<'
    { {         0}, {  0} },       
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 47} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 20} },                           
    { {       281}, { 48} }, // expression             
    { {       282}, { 49} }, // boolean_expression     
    { {       292}, { 50} }, // or_expression          
    { {       291}, { 51} }, // and_expression         
    { {       287}, { 52} }, // comparison_expression  
    { {       286}, { 53} }, // equality_expression    
    { {       285}, { 54} }, // greater_than_expression
    { {       283}, { 55} }, // less_than_expression   
    { {       284}, { 56} }, // arithmetic_expression  
    { {       294}, { 57} }, // add_expression         
    { {       293}, { 58} }, // mult_expression        
    { {       290}, { 59} }, // not_expression         
    { {        33}, { 60} }, // '!'                    
    { {       288}, { 61} }, // basic_expression       
    { {        40}, { 62} }, // '('                    
    { {       273}, { 63} }, // identifier             
    { {       289}, { 64} }, // constant               
    { {       258}, { 12} }, // NAME                   
    { {       257}, { 65} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 20} },                           
    { {       281}, { 66} }, // expression             
    { {       282}, { 49} }, // boolean_expression     
    { {       292}, { 50} }, // or_expression          
    { {       291}, { 51} }, // and_expression         
    { {       287}, { 52} }, // comparison_expression  
    { {       286}, { 53} }, // equality_expression    
    { {       285}, { 54} }, // greater_than_expression
    { {       283}, { 55} }, // less_than_expression   
    { {       284}, { 56} }, // arithmetic_expression  
    { {       294}, { 57} }, // add_expression         
    { {       293}, { 58} }, // mult_expression        
    { {       290}, { 59} }, // not_expression         
    { {        33}, { 60} }, // '!'                    
    { {       288}, { 61} }, // basic_expression       
    { {        40}, { 62} }, // '('                    
    { {       273}, { 63} }, // identifier             
    { {       289}, { 64} }, // constant               
    { {       258}, { 12} }, // NAME                   
    { {       257}, { 65} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 67} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 68} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   2} },       
    { {     124}, {  69} }, // '|'
    { {       0}, { -44} },       
};

SR__ s_51[] =
{
    { { REQ_DEF}, {   2} },       
    { {      38}, {  70} }, // '&'
    { {       0}, { -43} },       
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   3} },       
    { {      61}, {  71} }, // '='
    { {      33}, {  72} }, // '!'
    { {       0}, { -34} },       
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   2} },       
    { {      62}, {  73} }, // '>'
    { {       0}, { -33} },       
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   2} },       
    { {      60}, {  74} }, // '<'
    { {       0}, { -30} },       
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  75} }, // '+'
    { {      45}, {  76} }, // '-'
    { {       0}, { -51} },       
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  77} }, // '*'
    { {      47}, {  78} }, // '/'
    { {       0}, { -50} },       
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  9} },                    
    { {       290}, { 79} }, // not_expression  
    { {        33}, { 60} }, // '!'             
    { {       288}, { 61} }, // basic_expression
    { {        40}, { 62} }, // '('             
    { {       273}, { 63} }, // identifier      
    { {       289}, { 64} }, // constant        
    { {       258}, { 12} }, // NAME            
    { {       257}, { 65} }, // INTEGER_NUMBER  
    { {         0}, {  0} },                    
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 20} },                           
    { {       281}, { 80} }, // expression             
    { {       282}, { 49} }, // boolean_expression     
    { {       292}, { 50} }, // or_expression          
    { {       291}, { 51} }, // and_expression         
    { {       287}, { 52} }, // comparison_expression  
    { {       286}, { 53} }, // equality_expression    
    { {       285}, { 54} }, // greater_than_expression
    { {       283}, { 55} }, // less_than_expression   
    { {       284}, { 56} }, // arithmetic_expression  
    { {       294}, { 57} }, // add_expression         
    { {       293}, { 58} }, // mult_expression        
    { {       290}, { 59} }, // not_expression         
    { {        33}, { 60} }, // '!'                    
    { {       288}, { 61} }, // basic_expression       
    { {        40}, { 62} }, // '('                    
    { {       273}, { 63} }, // identifier             
    { {       289}, { 64} }, // constant               
    { {       258}, { 12} }, // NAME                   
    { {       257}, { 65} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 81} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  2} },                  
    { {       257}, { 82} }, // INTEGER_NUMBER
    { {         0}, {  0} },                  
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       279}, { 83} }, // goto_statement
    { {       263}, { 40} }, // GOTO          
    { {         0}, {  0} },                  
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       124}, { 84} }, // '|'
    { {         0}, {  0} },       
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        38}, { 85} }, // '&'
    { {         0}, {  0} },       
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 86} }, // '='
    { {         0}, {  0} },       
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 87} }, // '='
    { {         0}, {  0} },       
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 14} },                         
    { {       283}, { 88} }, // less_than_expression 
    { {        61}, { 89} }, // '='                  
    { {       284}, { 56} }, // arithmetic_expression
    { {       294}, { 57} }, // add_expression       
    { {       293}, { 58} }, // mult_expression      
    { {       290}, { 59} }, // not_expression       
    { {        33}, { 60} }, // '!'                  
    { {       288}, { 61} }, // basic_expression     
    { {        40}, { 62} }, // '('                  
    { {       273}, { 63} }, // identifier           
    { {       289}, { 64} }, // constant             
    { {       258}, { 12} }, // NAME                 
    { {       257}, { 65} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 13} },                         
    { {       284}, { 90} }, // arithmetic_expression
    { {        61}, { 91} }, // '='                  
    { {       294}, { 57} }, // add_expression       
    { {       293}, { 58} }, // mult_expression      
    { {       290}, { 59} }, // not_expression       
    { {        33}, { 60} }, // '!'                  
    { {       288}, { 61} }, // basic_expression     
    { {        40}, { 62} }, // '('                  
    { {       273}, { 63} }, // identifier           
    { {       289}, { 64} }, // constant             
    { {       258}, { 12} }, // NAME                 
    { {       257}, { 65} }, // INTEGER_NUMBER       
    { {         0}, {  0} },                         
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       293}, { 92} }, // mult_expression 
    { {       290}, { 59} }, // not_expression  
    { {        33}, { 60} }, // '!'             
    { {       288}, { 61} }, // basic_expression
    { {        40}, { 62} }, // '('             
    { {       273}, { 63} }, // identifier      
    { {       289}, { 64} }, // constant        
    { {       258}, { 12} }, // NAME            
    { {       257}, { 65} }, // INTEGER_NUMBER  
    { {         0}, {  0} },                    
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       293}, { 93} }, // mult_expression 
    { {       290}, { 59} }, // not_expression  
    { {        33}, { 60} }, // '!'             
    { {       288}, { 61} }, // basic_expression
    { {        40}, { 62} }, // '('             
    { {       273}, { 63} }, // identifier      
    { {       289}, { 64} }, // constant        
    { {       258}, { 12} }, // NAME            
    { {       257}, { 65} }, // INTEGER_NUMBER  
    { {         0}, {  0} },                    
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  9} },                    
    { {       290}, { 94} }, // not_expression  
    { {        33}, { 60} }, // '!'             
    { {       288}, { 61} }, // basic_expression
    { {        40}, { 62} }, // '('             
    { {       273}, { 63} }, // identifier      
    { {       289}, { 64} }, // constant        
    { {       258}, { 12} }, // NAME            
    { {       257}, { 65} }, // INTEGER_NUMBER  
    { {         0}, {  0} },                    
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  9} },                    
    { {       290}, { 95} }, // not_expression  
    { {        33}, { 60} }, // '!'             
    { {       288}, { 61} }, // basic_expression
    { {        40}, { 62} }, // '('             
    { {       273}, { 63} }, // identifier      
    { {       289}, { 64} }, // constant        
    { {       258}, { 12} }, // NAME            
    { {       257}, { 65} }, // INTEGER_NUMBER  
    { {         0}, {  0} },                    
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 96} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        62}, { 97} }, // '>'
    { {         0}, {  0} },       
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       262}, { 98} }, // ELSE
    { {         0}, {  0} },        
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, { 17} },                           
    { {       291}, { 99} }, // and_expression         
    { {       287}, { 52} }, // comparison_expression  
    { {       286}, { 53} }, // equality_expression    
    { {       285}, { 54} }, // greater_than_expression
    { {       283}, { 55} }, // less_than_expression   
    { {       284}, { 56} }, // arithmetic_expression  
    { {       294}, { 57} }, // add_expression         
    { {       293}, { 58} }, // mult_expression        
    { {       290}, { 59} }, // not_expression         
    { {        33}, { 60} }, // '!'                    
    { {       288}, { 61} }, // basic_expression       
    { {        40}, { 62} }, // '('                    
    { {       273}, { 63} }, // identifier             
    { {       289}, { 64} }, // constant               
    { {       258}, { 12} }, // NAME                   
    { {       257}, { 65} }, // INTEGER_NUMBER         
    { {         0}, {  0} },                           
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  16} },                           
    { {       287}, { 100} }, // comparison_expression  
    { {       286}, {  53} }, // equality_expression    
    { {       285}, {  54} }, // greater_than_expression
    { {       283}, {  55} }, // less_than_expression   
    { {       284}, {  56} }, // arithmetic_expression  
    { {       294}, {  57} }, // add_expression         
    { {       293}, {  58} }, // mult_expression        
    { {       290}, {  59} }, // not_expression         
    { {        33}, {  60} }, // '!'                    
    { {       288}, {  61} }, // basic_expression       
    { {        40}, {  62} }, // '('                    
    { {       273}, {  63} }, // identifier             
    { {       289}, {  64} }, // constant               
    { {       258}, {  12} }, // NAME                   
    { {       257}, {  65} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  14} },                           
    { {       285}, { 101} }, // greater_than_expression
    { {       283}, {  55} }, // less_than_expression   
    { {       284}, {  56} }, // arithmetic_expression  
    { {       294}, {  57} }, // add_expression         
    { {       293}, {  58} }, // mult_expression        
    { {       290}, {  59} }, // not_expression         
    { {        33}, {  60} }, // '!'                    
    { {       288}, {  61} }, // basic_expression       
    { {        40}, {  62} }, // '('                    
    { {       273}, {  63} }, // identifier             
    { {       289}, {  64} }, // constant               
    { {       258}, {  12} }, // NAME                   
    { {       257}, {  65} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  14} },                           
    { {       285}, { 102} }, // greater_than_expression
    { {       283}, {  55} }, // less_than_expression   
    { {       284}, {  56} }, // arithmetic_expression  
    { {       294}, {  57} }, // add_expression         
    { {       293}, {  58} }, // mult_expression        
    { {       290}, {  59} }, // not_expression         
    { {        33}, {  60} }, // '!'                    
    { {       288}, {  61} }, // basic_expression       
    { {        40}, {  62} }, // '('                    
    { {       273}, {  63} }, // identifier             
    { {       289}, {  64} }, // constant               
    { {       258}, {  12} }, // NAME                   
    { {       257}, {  65} }, // INTEGER_NUMBER         
    { {         0}, {   0} },                           
};

SR__ s_88[] =
{
    { { REQ_DEF}, {   2} },       
    { {      60}, {  74} }, // '<'
    { {       0}, { -28} },       
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  13} },                         
    { {       283}, { 103} }, // less_than_expression 
    { {       284}, {  56} }, // arithmetic_expression
    { {       294}, {  57} }, // add_expression       
    { {       293}, {  58} }, // mult_expression      
    { {       290}, {  59} }, // not_expression       
    { {        33}, {  60} }, // '!'                  
    { {       288}, {  61} }, // basic_expression     
    { {        40}, {  62} }, // '('                  
    { {       273}, {  63} }, // identifier           
    { {       289}, {  64} }, // constant             
    { {       258}, {  12} }, // NAME                 
    { {       257}, {  65} }, // INTEGER_NUMBER       
    { {         0}, {   0} },                         
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {  12} },                         
    { {       284}, { 104} }, // arithmetic_expression
    { {       294}, {  57} }, // add_expression       
    { {       293}, {  58} }, // mult_expression      
    { {       290}, {  59} }, // not_expression       
    { {        33}, {  60} }, // '!'                  
    { {       288}, {  61} }, // basic_expression     
    { {        40}, {  62} }, // '('                  
    { {       273}, {  63} }, // identifier           
    { {       289}, {  64} }, // constant             
    { {       258}, {  12} }, // NAME                 
    { {       257}, {  65} }, // INTEGER_NUMBER       
    { {         0}, {   0} },                         
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  77} }, // '*'
    { {      47}, {  78} }, // '/'
    { {       0}, { -48} },       
};

SR__ s_93[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  77} }, // '*'
    { {      47}, {  78} }, // '/'
    { {       0}, { -49} },       
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 105} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   3} },                  
    { {       279}, { 106} }, // goto_statement
    { {       263}, {  40} }, // GOTO          
    { {         0}, {   0} },                  
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   2} },       
    { {      38}, {  70} }, // '&'
    { {       0}, { -42} },       
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_101[] =
{
    { { REQ_DEF}, {   2} },       
    { {      62}, {  73} }, // '>'
    { {       0}, { -31} },       
};

SR__ s_102[] =
{
    { { REQ_DEF}, {   2} },       
    { {      62}, {  73} }, // '>'
    { {       0}, { -32} },       
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   2} },       
    { {      60}, {  74} }, // '<'
    { {       0}, { -29} },       
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 56 "new_parser.yy"
        {
         program_object.set_procedure_map(*current_procedure);
         if (d_vsp__[-3])
         d_vsp__[-3]->global_list_in_proc_map_check(get_line_number());
         delete d_vsp__[-3];
         }
        break;

        case 2:
#line 51 "new_parser.yy"
        d_val__ = d_vsp__[-1];
        {
         program_object.set_global_table(*d_vsp__[-1]);
         return_statement_used_flag = false; 
         }
        break;

        case 3:
#line 68 "new_parser.yy"
        {
         program_object.set_procedure_map(*current_procedure);
         }
        break;

        case 4:
#line 64 "new_parser.yy"
        d_val__ = d_vsp__[0];
        {
         return_statement_used_flag = false; 
         }
        break;

        case 5:
#line 75 "new_parser.yy"
        {
         current_procedure = new Procedure(void_data_type, *d_vsp__[-2].string_value);
         }
        break;

        case 6:
#line 87 "new_parser.yy"
        {
         if (return_statement_used_flag == false)
         {
         int line = get_line_number();
         report_error("Atleast 1 basic block should have a return statement", line);
         }
         current_procedure->set_basic_block_list(*d_vsp__[-1]);
         delete d_vsp__[-1];
         }
        break;

        case 7:
#line 82 "new_parser.yy"
        d_val__ = d_vsp__[-1];
        {
         current_procedure->set_local_list(*d_vsp__[0]);
         delete d_vsp__[0];
         }
        break;

        case 8:
#line 98 "new_parser.yy"
        {
         if (return_statement_used_flag == false)
         {
         int line = get_line_number();
         report_error("Atleast 1 basic block should have a return statement", line);
         }
         current_procedure->set_basic_block_list(*d_vsp__[-1]);
         delete d_vsp__[-1];
         }
        break;

        case 9:
#line 111 "new_parser.yy"
        {
         
         
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0]->get_variable_name(), line);
         string var_name = d_vsp__[0]->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         if (d_vsp__[-1] != NULL)
         {
         if(d_vsp__[-1]->variable_in_symbol_list_check(var_name))
         {
         int line = get_line_number();
         report_error("Variable is declared twice", line);
         }
         d_val__ = d_vsp__[-1];
         }
         else
         d_val__ = new Symbol_Table();
         d_val__->push_symbol(d_vsp__[0]);
         }
        break;

        case 10:
#line 138 "new_parser.yy"
        {
         int line = get_line_number();
         program_object.variable_in_proc_map_check(d_vsp__[0]->get_variable_name(), line);
         string var_name = d_vsp__[0]->get_variable_name();
         if (current_procedure && current_procedure->get_proc_name() == var_name)
         {
         int line = get_line_number();
         report_error("Variable name cannot be same as procedure name", line);
         }
         d_val__ = new Symbol_Table();
         d_val__->push_symbol(d_vsp__[0]);
         }
        break;

        case 11:
#line 156 "new_parser.yy"
        {
         d_val__ = new Symbol_Table_Entry(*d_vsp__[-1], int_data_type);
         delete d_vsp__[-1];
         }
        break;

        case 12:
#line 164 "new_parser.yy"
        {
         if (!d_vsp__[0])
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         bb_strictly_increasing_order_check(d_val__, d_vsp__[0]->get_bb_number());
         d_val__ = d_vsp__[-1];
         d_val__->push_back(d_vsp__[0]);
         }
        break;

        case 13:
#line 176 "new_parser.yy"
        {
         if (!d_vsp__[0])
         {
         int line = get_line_number();
         report_error("Basic block doesn't exist", line);
         }
         d_val__ = new list<Basic_Block *>;
         d_val__->push_back(d_vsp__[0]);
         }
        break;

        case 54:
#line 309 "new_parser.yy"
        {
         Symbol_Table_Entry var_table_entry;
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value);
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = program_object.get_symbol_table_entry(*d_vsp__[0].string_value);
         else
         {
         int line = get_line_number();
         report_error("Variable has not been declared", line);
         }
         d_val__ = new Name_Ast(*d_vsp__[0].string_value, var_table_entry);
         delete d_vsp__[0].string_value;
         }
        break;

        case 55:
#line 331 "new_parser.yy"
        {
         #if 0
         d_val__ = new Number_Ast<int>(d_vsp__[0].integer_value, int_data_type);
         #endif 
         }
        break;

    }
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}




